export const SOCKET_EVENTS = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  JOIN_PROJECT: "JOIN_PROJECT",
  SEND_MESSAGE: "SEND_MESSAGE",
  TEAM_MESSAGE: "TEAM_MESSAGE",
  NEW_PROJECT_MESSAGE: "NEW_PROJECT_MESSAGE",
  USER_ONLINE: "USER_ONLINE",
  USER_OFFLINE: "USER_OFFLINE"
} as const;

export type SocketEvent = typeof SOCKET_EVENTS[keyof typeof SOCKET_EVENTS];
