import Navbar from "@/components/layout/Navbar";
import Sidebar from "@/components/layout/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Gazzow | User",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex bg-primary">
      <Navbar/>

      <div className="flex flex-1 overflow-hidden">
         <Sidebar />

        <main className="flex-1 text-white">{children}</main>
      </div>
    </div>
  );
}
